/**
 * Detachment data constants for Warhammer 40K.
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: mcp-server/src/scripts/generate-detachment-data.ts
 * Generated at: 2026-01-23T21:15:48.955Z
 *
 * To regenerate: npm run cli generate detachments
 */

// Army Detachments by faction
export const DETACHMENTS = [
  // Adepta Sororitas
  'Army of Faith',
  'Bringers of Flame',
  'Champions of Faith',
  'Hallowed Martyrs',
  'Penitent Host',
  // Adeptus Custodes
  'Auric Champions',
  'Lions of the Emperor',
  'Null Maiden Vigil',
  'Shield Host',
  'Solar Spearhead',
  'Talons Of The Emperor',
  // Adeptus Mechanicus
  'Cohort Cybernetica',
  'Data-Psalm Conclave',
  'Explorator Maniple',
  'Haloscreed Battle Clade',
  'Rad-Zone Corps',
  'Skitarii Hunter Cohort',
  // Aeldari
  'Armoured Warhost',
  'Aspect Host',
  'Devoted of Ynnead',
  'Ghosts of the Webway',
  'Guardian Battlehost',
  'Seer Council',
  'Serpent’s Brood',
  'Spirit Conclave',
  'Warhost',
  'Windrider Host',
  // Astra Militarum
  'Combined Arms',
  'Mechanised Assault',
  'Siege Regiment',
  // Chaos Daemons
  'Blood Legion',
  'Daemonic Incursion',
  'Legion of Excess',
  'Plague Legion',
  'Scintillating Legion',
  'Shadow Legion',
  // Chaos Knights
  'Houndpack Lance',
  'Iconoclast Fiefdom',
  'Infernal Lance',
  'Lords of Dread',
  'Traitoris Lance',
  // Chaos Space Marines
  'Cabal of Chaos',
  'Chaos Cult',
  'Creations of Bile',
  'Deceptors',
  'Dread Talons',
  'Fellhammer Siege-host',
  'Nightmare Hunt',
  'Pactbound Zealots',
  'Renegade Raiders',
  'Soulforged Warpack',
  'Veterans of the Long War',
  // Death Guard
  'Champions of Contagion',
  'Death Lord’s Chosen',
  'Mortarion’s Hammer',
  'Shamblerot Vectorium',
  'Tallyband Summoners',
  'Virulent Vectorium',
  // Drukhari
  'Covenite Coterie',
  'Kabalite Cartel',
  'Realspace Raiders',
  'Reaper’s Wager',
  'Skysplinter Assault',
  'Spectacle of Spite',
  // Genestealer Cults
  'Biosanctic Broodsurge',
  'Brood Brother Auxilia',
  'Final Day',
  'Host of Ascension',
  'Outlander Claw',
  'Xenocreed Congregation',
  // Grey Knights
  'Augurium Task Force',
  'Banishers',
  'Brotherhood Strike',
  'Hallowed Conclave',
  'Sanctic Spearhead',
  'Warpbane Task Force',
  // Imperial Agents
  'Imperialis Fleet',
  'Ordo Hereticus Purgation Force',
  'Ordo Malleus Daemon Hunters',
  'Ordo Xenos Alien Hunters',
  'Veiled Blade Elimination Force',
  // Imperial Knights
  'Gate Warden Lance',
  'Questor Forgepact',
  'Questoris Companions',
  'Spearhead-At-Arms',
  'Valourstrike Lance',
  // Leagues of Votann
  'Brandfast Oathband',
  'Dêlve Assault Shift',
  'Hearthband',
  'Hearthfyre Arsenal',
  'Needgaârd Oathband',
  'Persecution Prospect',
  // Necrons
  'Annihilation Legion',
  'Awakened Dynasty',
  'Canoptek Court',
  'Cryptek Conclave',
  'Cursed Legion',
  'Hypercrypt Legion',
  'Obeisance Phalanx',
  'Pantheon of Woe',
  'Starshatter Arsenal',
  // Orks
  'Bully Boyz',
  'Da Big Hunt',
  'Dread Mob',
  'Green Tide',
  'Kult of Speed',
  'More Dakka!',
  'Taktikal Brigade',
  'War Horde',
  // Space Marines
  '1st Company Task Force',
  'Anvil Siege Force',
  'Bastion Task Force',
  'Firestorm Assault Force',
  'Gladius Task Force',
  'Ironstorm Spearhead',
  'Librarius Conclave',
  'Orbital Assault Force',
  'Stormlance Task Force',
  'Vanguard Spearhead',
  // Thousand Sons
  'Changehost of Deceit',
  'Grand Coven',
  'Hexwarp Thrallband',
  'Rubricae Phalanx',
  'Warpforged Cabal',
  'Warpmeld Pact',
  // Tyranids
  'Assimilation Swarm',
  'Crusher Stampede',
  'Invasion Fleet',
  'Subterranean Assault',
  'Synaptic Nexus',
  'Unending Swarm',
  'Vanguard Onslaught',
  'Warrior Bioform Onslaught',
  // T’au Empire
  'Auxiliary Cadre',
  'Experimental Prototype Cadre',
  'Kauyon',
  'Kroot Hunting Pack',
  'Mont’ka',
  'Retaliation Cadre',
  // World Eaters
  'Berzerker Warband',
  'Cult of Blood',
  'Goretrack Onslaught',
  'Khorne Daemonkin',
  'Possessed Slaughterband',
  'Vessels of Wrath',
] as const;

// Common aliases for detachments (colloquial -> canonical)
export const DETACHMENT_ALIASES = new Map<string, string>([
  ['cartel', 'Kabalite Cartel'],
  ['cabalite cartel', 'Kabalite Cartel'],
  ['sky-splinter', 'Skysplinter Assault'],
  ['sky splinter', 'Skysplinter Assault'],
  ['sky-splinter assault', 'Skysplinter Assault'],
  ['sky splinter assault', 'Skysplinter Assault'],
  ['gladius', 'Gladius Task Force'],
  ['ironstorm', 'Ironstorm Spearhead'],
  ['firestorm', 'Firestorm Assault Force'],
  ['vanguard', 'Vanguard Spearhead'],
  ['1st company', 'First Company Task Force'],
  ['first company', 'First Company Task Force'],
  ['stormlance', 'Stormlance Task Force'],
  ['awakened', 'Awakened Dynasty'],
  ['canoptek', 'Canoptek Court'],
  ['hypercrypt', 'Hypercrypt Legion'],
  ['obeisance', 'Obeisance Phalanx'],
  ['invasion', 'Invasion Fleet'],
  ['crusher', 'Crusher Stampede'],
  ['synaptic', 'Synaptic Nexus'],
  ['assimilation', 'Assimilation Swarm'],
  ['unending', 'Unending Swarm'],
  ['shield host', 'Shield Host'],
  ['auric', 'Auric Champions'],
  ['talons', 'Talons of the Emperor'],
  ['null maiden', 'Null Maiden Vigil'],
  ['waaagh', 'Waaagh! Tribe'],
  ['war horde', 'War Horde'],
  ['bully boyz', 'Bully Boyz'],
  ['kult of speed', 'Kult of Speed'],
  ['speed freeks', 'Kult of Speed'],
  ['dread mob', 'Dread Mob'],
  ['green tide', 'Green Tide'],
  ['kauyon', 'Kauyon'],
  ['montka', "Mont'ka"],
  ["mont'ka", "Mont'ka"],
  ['retaliation', 'Retaliation Cadre'],
  ['slaves to darkness', 'Slaves to Darkness'],
  ['veterans', 'Veterans of the Long War'],
  ['pactbound', 'Pactbound Zealots'],
  ['deceptors', 'Deceptors'],
  ['dread talons', 'Dread Talons'],
  ['soulforged', 'Soulforged Warpack'],
  ['battle host', 'Battle Host'],
  ['windrider', 'Windrider Host'],
  ['starhost', 'Starhost'],
  ['teleport strike', 'Teleport Strike Force'],
  ['warp bane', 'Teleport Strike Force'],
  ['plague company', 'Plague Company'],
  ['creeping death', 'Creeping Death'],
  ['berzerker', 'Berzerker Warband'],
  ['cult of magic', 'Cult of Magic'],
]);

export type Detachment = typeof DETACHMENTS[number];

/** Get all detachment names */
export function getAllDetachments(): string[] {
  return [...DETACHMENTS];
}

/** Resolve an alias to its canonical name */
export function resolveDetachmentAlias(name: string): string {
  const normalized = name.toLowerCase().trim();
  return DETACHMENT_ALIASES.get(normalized) ?? name;
}
