/**
 * Generate stratagem data from MCP server database.
 *
 * This script queries the database for all stratagems and generates
 * a JSON file for use in the transcript preprocessor.
 *
 * Usage:
 *   npm run cli codegen stratagems
 */

import 'dotenv/config';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { getDb } from '../db/connection.js';
import { stratagems } from '../db/schema.js';

// Output to root src/data/generated
const OUTPUT_DIR = join(process.cwd(), '..', 'src', 'data', 'generated');

interface GeneratedStratagemData {
  names: string[];
  coreStratagems: string[];
  aliases: Record<string, string>;
  generatedAt: string;
}

// Common aliases for stratagems (colloquial -> canonical)
const STRATAGEM_ALIASES: Record<string, string> = {
  overwatch: 'fire overwatch',
  're-roll': 'command re-roll',
  reroll: 'command re-roll',
  'counter offensive': 'counter-offensive',
  'go to ground': 'go to ground',
};

async function main() {
  console.log('Generating stratagem data from database...\n');

  // Ensure output directory exists
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  try {
    const db = getDb();

    // Query all stratagems
    console.log('Querying stratagems from database...');
    const allStratagems = await db.select().from(stratagems);

    if (allStratagems.length === 0) {
      console.warn('No stratagems found in database. Using fallback data.');
      writeFallbackData();
      return;
    }

    console.log(`   Found ${allStratagems.length} stratagems`);

    // Extract names
    const names = [...new Set(allStratagems.map((s) => s.name))].sort();

    // Extract core stratagems
    const coreStratagems = [
      ...new Set(allStratagems.filter((s) => s.isCore).map((s) => s.name)),
    ].sort();

    console.log(`   Core stratagems: ${coreStratagems.length}`);
    console.log(`   Faction stratagems: ${names.length - coreStratagems.length}`);

    const data: GeneratedStratagemData = {
      names,
      coreStratagems,
      aliases: STRATAGEM_ALIASES,
      generatedAt: new Date().toISOString(),
    };

    // Write JSON data
    const jsonPath = join(OUTPUT_DIR, 'stratagems.json');
    writeFileSync(jsonPath, JSON.stringify(data, null, 2));
    console.log(`\nWritten ${jsonPath}`);

    // Write TypeScript loader
    const tsContent = generateTypeScriptLoader(data);
    const tsPath = join(OUTPUT_DIR, 'stratagems.ts');
    writeFileSync(tsPath, tsContent);
    console.log(`Written ${tsPath}`);

    console.log(`\nGenerated stratagem data with ${names.length} stratagems`);
  } catch (error) {
    console.error('Database query failed:', error);
    console.warn('Using fallback data instead.');
    writeFallbackData();
  }

  process.exit(0);
}

function writeFallbackData() {
  // Fallback: use hardcoded stratagems if database is unavailable
  const fallbackData: GeneratedStratagemData = {
    names: [
      // Core stratagems
      'Fire Overwatch',
      'Go to Ground',
      'Smokescreen',
      'Rapid Ingress',
      'Heroic Intervention',
      'Counter-offensive',
      'Insane Bravery',
      'Grenade',
      'Tank Shock',
      'Command Re-roll',
      'Epic Challenge',
    ],
    coreStratagems: [
      'Fire Overwatch',
      'Go to Ground',
      'Smokescreen',
      'Rapid Ingress',
      'Heroic Intervention',
      'Counter-offensive',
      'Insane Bravery',
      'Grenade',
      'Tank Shock',
      'Command Re-roll',
      'Epic Challenge',
    ],
    aliases: STRATAGEM_ALIASES,
    generatedAt: new Date().toISOString(),
  };

  const jsonPath = join(OUTPUT_DIR, 'stratagems.json');
  writeFileSync(jsonPath, JSON.stringify(fallbackData, null, 2));
  console.log(`\nWritten fallback data to ${jsonPath}`);

  const tsContent = generateTypeScriptLoader(fallbackData);
  const tsPath = join(OUTPUT_DIR, 'stratagems.ts');
  writeFileSync(tsPath, tsContent);
  console.log(`Written ${tsPath}`);

  console.log(`\nUsing fallback stratagem data (${fallbackData.names.length} stratagems)`);
}

function generateTypeScriptLoader(data: GeneratedStratagemData): string {
  return `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by mcp-server/scripts/generate-stratagem-data.ts
// Generated at: ${data.generatedAt}

import stratagemData from './stratagems.json';

export interface StratagemData {
  names: string[];
  coreStratagems: string[];
  aliases: Record<string, string>;
  generatedAt: string;
}

const data = stratagemData as StratagemData;

/** All stratagem names for transcript matching */
export const STRATAGEM_NAMES: string[] = data.names;

/** Core stratagems available to all armies */
export const CORE_STRATAGEMS: string[] = data.coreStratagems;

/** Map of colloquial names to canonical stratagem names */
export const STRATAGEM_ALIASES: Map<string, string> = new Map(
  Object.entries(data.aliases)
);

/** Get all stratagems (core + faction) */
export function getAllStratagems(): string[] {
  return [...STRATAGEM_NAMES];
}

/** Check if a name is a core stratagem */
export function isCoreStratagem(name: string): boolean {
  const normalized = name.toLowerCase().trim();
  return CORE_STRATAGEMS.some((s) => s.toLowerCase() === normalized);
}

/** Resolve an alias to its canonical name */
export function resolveStratagemAlias(name: string): string {
  const normalized = name.toLowerCase().trim();
  return STRATAGEM_ALIASES.get(normalized) ?? name;
}
`;
}

main().catch((error) => {
  console.error('Generation failed:', error);
  process.exit(1);
});
